version: '3'
services:
  api:
    build: .
    container_name: flask_api
    depends_on:
      - db
    env_file: secrets.env
    image: flask_api
    links:
      - db
    ports:
      - '5000:5000'
    volumes:
      - ./src:/usr/src/app

  db:
    build: ./postgres
    container_name: flask_api_db
    env_file: secrets.env
    image: flask_api_db
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data
